name: Integração Contínua

on:
  pull_request:
    branches:
      - main

  push:
    
jobs:
  executar_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o checkout
        uses: actions/checkout@v2

      - name: Instala o Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Instala o pip3 e dependencias
        uses: luisgs7/pip3-packages@v1.0.4

      - name: Instala as dependências
        run: pip3 install -r requirements.txt

      - name: Executa o black
        run: black --check app

      - name: Executa os testes unitários
        run: pytest -v 